### ISSUE TITLE
Billboarding Issue with Polyline

### ISSUE THREAD

**Issue by dthian** [viromedia/virocore#179] opened 2018-08-02 23:21 UTC
If you draw a continuous Polyline into the scene, you will notice that it distorts near the edges of 90 degrees. Thus, in VR this occurs directly above, below and to the left and right of the camera at it's origin rotation. You can see that here: 

![screen shot 2018-08-02 at 4 21 08 pm](https://user-images.githubusercontent.com/1904934/43616197-2782ea34-9670-11e8-850a-e6b94a3de6bf.png)

**Comment by LaraRode** [comment] 2018-09-05 21:01
Hi there! First off, thanks ViroCore team for always being responsive and helpful.
I was just wondering if I can expect any progress on this issue any time soon, I was hoping to use it in my application if possible.  If not, I will continue to look into other possible solutions.
Thanks!

**Comment by VikAdvani** [comment] 2018-09-08 00:01
Hi @LaraRode, we are hoping to get this fixed in the next ViroCore release. We've identified the issue. I'll update this thread when the issue is fixed.

**Comment by dam00n** [comment] 2018-09-20 21:58
Hi @LaraRode this issue has been fixed in the latest release, ViroCore v1.11.0

Release notes and upgrade instructions here -> https://virocore.viromedia.com/docs/releases

Closing the issue. Please re-open if you are still having problems.

**Closed by dam00n** 2018-09-20 21:58 UTC
