### ISSUE TITLE
The color is very dark for the recording video.

### ISSUE THREAD

**Issue by EricSKCheng** [viromedia/virocore#44] opened 2018-03-11 01:55 UTC
The color is very dark for the recording video, however the color of the screen shot is fine.
Tested on Google pixel 2 with ViroViewARCore api.

**Comment by 544531645** [comment] 2018-03-12 06:42
same

**Comment by dthian** [comment] 2018-03-12 21:09
Hey all, thanks for reaching out! I've root caused this bug in the ViroMediaRecorder - basically the video isn't properly corrected to sRGB space, resulting in an over-saturated visual output. I've filed a bug on this, we'll be working on a fix and will update this issue as soon as it has been pushed to release.

**Comment by dam00n** [comment] 2018-03-30 13:33
This issue has been fixed in the latest update, ViroCore 1.5. Release notes and upgrade instructions here -> https://virocore.viromedia.com/docs/releases

Let us know if you are still having issues after upgrading.

**Closed** 2018-04-09 16:49 UTC
